[project]
name = "japan-safe-cycling-map"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "TAKAHASHI Shuuji", email = "id@shuuji3.xyz" }
]
requires-python = ">=3.14"
dependencies = [
    "osmium>=4.3.1",
]

[project.scripts]
safe-cycling-map = "safe_cycling_map:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
